init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Bootstrap
        Progress "Downloading external software"
        md C:\Rextsoft
        Invoke-WebRequest http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local320.zip -OutFile "C:\Rextsoft\local320.zip"
        7z x C:\Rextsoft\local320.zip -oC:\Rextsoft -r
        Rscript -e "m <- readLines('E:/R/etc/i386/Makeconf'); m <- paste0(sub('^LOCAL_SOFT = d:/RCompile/r-compiling/local/local320$', 'LOCAL_SOFT = C:/Rextsoft', m), '\n', collapse='\n'); f <- file('E:/R/etc/i386/Makeconf', 'wb'); writeChar(m, f, eos = NULL); close(f)"
        Rscript -e "m <- readLines('E:/R/etc/x64/Makeconf'); m <- paste0(sub('^LOCAL_SOFT = d:/RCompile/r-compiling/local/local320$', 'LOCAL_SOFT = C:/Rextsoft', m), '\n', collapse='\n'); f <- file('E:/R/etc/x64/Makeconf', 'wb'); writeChar(m, f, eos = NULL); close(f)"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
